//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tbTpNews {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtTPName;
		protected global::System.Web.UI.WebControls.TextBox txtTPEasyContent;
		protected global::System.Web.UI.WebControls.TextBox txtTPContent;
		protected global::System.Web.UI.WebControls.TextBox txtTPImgUrl;
		protected global::System.Web.UI.WebControls.TextBox txtTPBianJi;
		protected global::System.Web.UI.WebControls.TextBox txtTPFuShu1;
		protected global::System.Web.UI.WebControls.TextBox txtisDel;
		protected global::System.Web.UI.WebControls.TextBox txtFatherId;
		protected global::System.Web.UI.WebControls.TextBox txtDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtOrderBy;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
